'use strict';

const { Command } = require('commander');
const ora = require('ora');
const chalk = require('chalk');
const fs = require('fs');
const path = require('path');
const Config = require('../config');
const AiClient = require('../lib/ai-client');
const CicdClient = require('../lib/cicd-client');
const output = require('../utils/output');
const { handleError } = require('../utils/errors');

const releaseNotesCmd = new Command('release-notes')
  .description('Auto-generate release notes for a sprint or user story')
  .option('--sprint <name>', 'Sprint name (e.g. "Sprint 42")')
  .option('--us <id>', 'Single user story ID')
  .option('--save', 'Save release notes to a markdown file')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const story = opts.us || Config.getCurrentStory()?.id;
    const sprint = opts.sprint;

    if (!story && !sprint) {
      output.error('Please provide --sprint <name> or --us <id>');
      output.dim('Example: copado-hx release-notes --sprint "Sprint 42"');
      output.dim('Example: copado-hx release-notes --us US-1234');
      process.exit(1);
    }

    output.blank();
    console.log(chalk.bold.hex('#7F77DD')('📝 RELEASE NOTES GENERATOR'));
    console.log(chalk.dim('─'.repeat(50)));
    output.blank();

    const spinner = ora('Generating release notes with Release Agent...').start();

    try {
      const prompt = sprint
        ? `Generate professional release notes for ${sprint}.
           Include:
           1. Executive Summary (2-3 sentences)
           2. New Features & Enhancements
           3. Bug Fixes
           4. Technical Changes
           5. Deployment Notes
           6. Known Issues (if any)
           Format it as clean markdown.`
        : `Generate professional release notes for Copado user story ${story}.
           Include:
           1. Summary of changes
           2. Business impact
           3. Technical details
           4. Testing notes
           5. Deployment instructions
           Format it as clean markdown.`;

      const { dialogueId, response } = await AiClient.ask(
        'release',
        prompt,
        story
      );

      spinner.stop();

      const text = extractText(response);
      const title = sprint || `US-${story}`;
      const timestamp = new Date().toISOString().split('T')[0];

      if (opts.json) {
        return output.json({ title, timestamp, dialogueId, notes: text });
      }

      // Pretty print
      console.log(chalk.bold.white(`Release Notes — ${title}`));
      console.log(chalk.dim(`Generated: ${timestamp}`));
      console.log(chalk.dim('─'.repeat(50)));
      output.blank();
      console.log(text);
      output.blank();

      // Save to file if requested
      if (opts.save) {
        const filename = `release-notes-${title.replace(/\s+/g, '-').toLowerCase()}-${timestamp}.md`;
        const filepath = path.join(process.cwd(), filename);
        const content = `# Release Notes — ${title}\n\n> Generated by copado-hx on ${timestamp}\n\n${text}`;
        fs.writeFileSync(filepath, content, 'utf8');
        output.success(`Saved to ${chalk.cyan(filename)}`);
      } else {
        output.dim('Tip: Add --save to export as a markdown file!');
      }

      output.blank();

    } catch (err) {
      spinner.stop();
      handleError(err, opts.json);
    }
  });

function extractText(response) {
  if (typeof response === 'string') return response;
  if (response?.message) return response.message;
  if (response?.content) return response.content;
  if (response?.text) return response.text;
  if (response?.response) return response.response;
  return JSON.stringify(response, null, 2);
}

module.exports = releaseNotesCmd;